config/routes.rb
Tarantula::Application.routes.draw do
  root :to => "home#index"
  
  resource :archive, :only => [:destroy, :create],
    :path => '/projects/:project_id/:resources/archive',
    :controller => 'archives'

  resources :password_resets

  resources :projects do
    member do
      get :priorities
      delete :deleted
      get :products
    end
    
    collection do
      get :deleted
    end

    resources :users do
      resources :executions
      resource :test_area
      resource :test_object
      resources :report_data
    end

    resources :test_sets do
      resources :cases do
        collection do
          get :not_in_set
        end
      end
    end
    resources :attachments
    resources :cases
    resources :executions
    resources :requirements
    resources :tags
    resources :tasks
    resources :test_objects do
      resources :attachments
    end
    resources :test_areas
    
    resources :bug_trackers do
      member do
        get :products
      end
    end
    
    resources :bugs
  end

  resources :requirements do
    resources :cases, :only => [:index]
    resources :attachments
  end

  resources :test_sets do
    resources :cases do
      collection do
        get :not_in_set
      end
    end
  end

  resources :cases do
    member do
      get :change_history
    end
    resources :attachments
    resources :tasks
    resources :requirements, :only => [:index]
  end

  resources :case_executions do
    resources :attachments
  end

  resources :executions do
    resources :case_executions
  end

  resources :test_objects, :only => [:show] do
    resources :attachments
  end

  resources :users do
    member do
      put :selected_project
      get :permissions
      get :available_groups
    end
    collection do
      get :deleted
    end
    
    resources :projects do
      member do
        get :group
      end
      collection do
        get :deleted
      end
    end
    resources :executions
    resources :tasks
  end

  resources :bug_trackers do
    member do
      get :products
    end
  end

  resources :customer_configs
  match 'restart', :to => 'customer_configs#restart', via: [:get, :post]
  
  resource :report, :controller => 'report' do
    member do
      get :dashboard
      get :test_result_status
      get :results_by_test_object
      get :case_execution_list
      get :test_efficiency
      get :status
      get :requirement_coverage
      get :bug_trend
      get :workload
    end
  end
  
  resource :home, :controller => 'home' do
    member do
      get :login
      post :login
      get :logout
      get :index
    end
  end               

  resource :import, :controller => 'import' do
    member do
      get :doors
      post :doors
    end
  end

  resources :backups, :only => [:new, :create]
  resources :csv_exports, :only => [:new, :create]
  resources :csv_imports, :only => [:new, :create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if request.xhr? == true
      render :layout => false
    else
      render :layout => "inside"
    end
  end
  
  def login
    if request.post?
      if u = User.authenticate(params[:login], params[:password])
        if !u.latest_project
          flash.now[:notice] = "You have no project assignments."
          return false
        elsif u.deleted?
          flash.now[:notice] = "You have been deleted."
          return false
        else
          session[:user_id] = u.id
          redirect_to :action => 'index'
        end
        return
      end
      session[:user_id] = nil
      flash.now[:notice] = "Login failed."
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to :action => 'login'
  end
  
end

app/views/home/login.html.erb
<div id="loginform">
  <img src="<%= asset_path 'tarantula/logo.gif' %>" alt="Testia Tarantula" />

  <div style="margin-left: 10px">
    <%= form_tag(:controller => 'home', :action => 'login') do %>
    <div class="x-form-ct">
      <div class="x-form-item">
        <label for="login">Username</label>
        <div class="x-form-element">
          <%= text_field_tag 'login', '', :class => 'x-form-text x-form-field' %>
        </div>
      </div>
      <div class="x-form-item">
        <label for="password">Password</label>
        <div class="x-form-element">
          <%= password_field_tag 'password', '', :class => 'x-form-text x-form-field' %>
        </div>
      </div>
      <%= submit_tag 'Log in', :style => 'display:none;' %>
    </div>
    <div class="x-form-btns-ct">
      <div onclick="document.forms[0].submit();" class="x-form-btns">
        <table cellspacing="0">
          <tbody>
            <tr><td class="x-form-btn-td">
                <table cellspacing="0" cellpadding="0" border="0" style="width: 75px;" class="x-btn-wrap x-btn">
                  <tbody>
                    <tr><td class="x-btn-left"/>
                      <td class="x-btn-center">
                        <em>
                          Login
                        </em>
                      </td>
                      <td class="x-btn-right">
                      </td>
                    </tr>
                  </tbody>
                </table>
            </td></tr>
          </tbody>
        </table>
        <div class="x-clear"/>
      </div>
    </div>
    <% end %>
    <div style="margin: 10px 0 0 0;"><%= flash[:notice] %></div>
  </div>

  <div id="forgot_link" style="margin: 50px 0 0 10px; font-size: 15px;">
    <%= link_to "Forgot Password?", "javascript:Element.toggle('forgot');" %>
  </div>

  <div id="forgot" style="margin: 10px 0 0 10px; font-size: 12px; display:none;">
    Please enter your user name or email address:<br/>
    <form action="<%= password_resets_path %>" method="post" onsubmit="new Ajax.Request('<%= password_resets_path %>', {parameters: {name_or_email: $F('name_or_email')}}); return false;">
    <%= text_field_tag :name_or_email, '', :class => 'x-form-text x-form-field' %>
    <%= submit_tag 'Send' %>
    </form>
    <div id="errors"></div>
  </div>

  <div class="version">
    <p>Release <%= Testia::VERSION %></p>
    <p class="copyright">Copyright &copy; 2008-2011, Prove Testia Oy</p>
    <p>Licensed under GPL Version 3</p>
  </div>

</div>